/// Step 420 (BLGTA-017-06) -- "silently capture the unique mobile device ID",
/// which the operating systems will not give you and the framework will not
/// allow.
///
/// The row: "Configure the mobile application network gateway to silently
/// capture the unique mobile device ID upon submission."
/// Metric: **Process Execution Quality Score** -- floor ">=90%", optimal
/// ">=98%", ceiling "1". Best Qualitative Output: "Good/Average/Poor -> Best =
/// Good (100%)". ISO 9001:2015 Quality Management Standard. Assigned to
/// **UDF**.
///
/// **There is no unique mobile device ID to capture.** Android removed
/// non-resettable hardware identifiers from ordinary applications years ago;
/// iOS gives an advertising identifier only after an explicit tracking prompt
/// the user can refuse, and a vendor identifier that resets when the last app
/// from that vendor is removed. An instruction to capture a permanent device
/// identifier is an instruction the platform declines, so a build that appears
/// to satisfy it is either using a fingerprint assembled from other signals or
/// quietly failing.
///
/// **What the requirement is for is legitimate, and is served.** A gateway
/// wants to know that two submissions came from the same device -- duplicate
/// detection, replay, and one account filing the same claim four times. That
/// needs a value that is stable per install, unique enough to collide rarely,
/// and useless anywhere else. A random identifier generated on first run,
/// stored in the app's own keychain entry, salted per environment, rotated when
/// the app is reinstalled, and never sent to anybody but this gateway does that
/// job completely, and does nothing else.
///
/// **"Silently" is refused for the second time in four rows.** Step 417 split
/// the word into a property of the implementation and a property of the
/// relationship, built the first and refused the second. The same split holds
/// here: the capture is silent in the sense that it costs no interaction and no
/// visible step, and it is disclosed on the surface Step 417 named. This is the
/// second row in this batch whose literal reading builds surveillance and whose
/// requirement is met without it.
///
/// **The band mixes units and the output carries an arrow.** Two percentages
/// and a ceiling of 1, with "Best = Good (100%)" spelled out in the output
/// column -- the fourth mixed-unit band in two batches and the seventh
/// arrow-annotated output cell.
library;

import 'friction_indicators.dart';
import 'tracking_sdk.dart';

/// A kind of identifier the row might have meant.
enum HabotIdentifierKind {
  /// IMEI, serial, MAC. Unavailable to ordinary applications.
  hardware,

  /// The advertising identifier. Consent-gated and resettable.
  advertising,

  /// A vendor identifier. Resets when the vendor's last app is removed.
  vendor,

  /// Generated by this app, stored by this app, meaningless elsewhere.
  appScopedInstall,
}

/// The install identifier, in place of a device identifier.
class HabotDeviceIdentifier {
  const HabotDeviceIdentifier._();

  // -----------------------------------------------------------------------
  // The platform will not give you one.
  // -----------------------------------------------------------------------

  static const Map<HabotIdentifierKind, String> availability =
      <HabotIdentifierKind, String>{
    HabotIdentifierKind.hardware:
        'not available to ordinary applications on either platform',
    HabotIdentifierKind.advertising:
        'available only after an explicit prompt the user may refuse, and '
            'resettable at any time',
    HabotIdentifierKind.vendor:
        'resets when the last application from this vendor is removed',
    HabotIdentifierKind.appScopedInstall:
        'generated here, stored here, and meaningless to anybody else',
  };

  static bool get everyKindIsAssessed =>
      availability.length == HabotIdentifierKind.values.length;

  static const HabotIdentifierKind chosen =
      HabotIdentifierKind.appScopedInstall;

  static bool get theHardwareIdIsUnavailable =>
      (availability[HabotIdentifierKind.hardware] ?? '')
          .contains('not available');

  static const bool aFingerprintIsAssembled = false;

  static bool get noFingerprintIsAssembled => !aFingerprintIsAssembled;

  static const String platformNote =
      'Android removed non-resettable hardware identifiers from ordinary '
      'applications years ago and iOS gates its advertising identifier behind '
      'a prompt the user can refuse. An instruction to capture a permanent '
      'device identifier is an instruction the platform declines, so an '
      'implementation that appears to satisfy it is either assembling a '
      'fingerprint out of model, locale and screen metrics -- which is the '
      'same act under a different name -- or failing quietly. Neither is done '
      'here.';

  // -----------------------------------------------------------------------
  // What the gateway actually needs.
  // -----------------------------------------------------------------------

  static const String whatTheGatewayNeeds =
      'to know that two submissions came from the same install';

  static const String whatItDoesNotNeed =
      'to know which person or which handset';

  static bool get theNeedIsNarrowerThanTheInstruction =>
      whatTheGatewayNeeds != whatItDoesNotNeed;

  static const bool generatedOnFirstRun = true;
  static const bool storedInTheAppsOwnKeychainEntry = true;
  static const bool saltedPerEnvironment = true;
  static const bool rotatesOnReinstall = true;
  static const bool sentToAnyoneElse = false;
  static const bool survivesUninstall = false;

  static bool get theIdentifierIsAppScoped =>
      generatedOnFirstRun &&
      storedInTheAppsOwnKeychainEntry &&
      saltedPerEnvironment &&
      !sentToAnyoneElse;

  static bool get itCannotBeJoinedAcrossApps =>
      saltedPerEnvironment && !sentToAnyoneElse;

  static bool get itDoesNotOutliveTheInstall =>
      rotatesOnReinstall && !survivesUninstall;

  static const int propertiesDeclared = 6;

  static const String designNote =
      'A random value generated on first run, kept in this application\'s own '
      'keychain entry, salted per environment, rotated on reinstall and sent '
      'to nobody but this gateway answers the duplicate-submission question '
      'completely and answers nothing else. It cannot be joined to another '
      'application\'s data, it does not outlive the install, and losing it '
      'costs the gateway one false negative rather than a person their '
      'privacy.';

  // -----------------------------------------------------------------------
  // "Silently", for the second time in four rows.
  // -----------------------------------------------------------------------

  static bool get theWordWasSplitAtStep417 =>
      HabotFrictionIndicators.theTwoReadingsDiffer;

  static const bool captureCostsAnInteraction = false;

  static const bool theCaptureIsDisclosed = true;

  static bool get silentInTheBuildableSense => !captureCostsAnInteraction;

  static bool get notSilentInTheOtherSense => theCaptureIsDisclosed;

  static bool get theDisclosureSurfaceIsTheOneStep417Named =>
      HabotFrictionIndicators.disclosureSurface.contains('Privacy');

  /// Steps 417 and 420.
  static const List<int> rowsRefusingTheSecrecyReading = <int>[417, 420];

  static bool get secondRefusalInThisBatch =>
      rowsRefusingTheSecrecyReading.length == 2;

  static const String silenceNote =
      'Step 417 split "silently" into a property of the implementation and a '
      'property of the relationship, built the first and refused the second. '
      'The same split holds here: the capture costs no tap and no visible '
      'step, and it appears on the disclosure surface with the friction '
      'indicators. Two rows in this batch read literally would build '
      'surveillance, and both requirements are met without it.';

  // -----------------------------------------------------------------------
  // A mixed-unit band and an arrow.
  // -----------------------------------------------------------------------

  static const String bandFloorRaw = '>=90%';
  static const String bandOptimalRaw = '>=98%';
  static const String bandCeilingRaw = '1';

  static bool get theBandMixesUnits =>
      bandFloorRaw.contains('%') &&
      bandOptimalRaw.contains('%') &&
      !bandCeilingRaw.contains('%');

  static const String outputColumnRaw =
      'Good/Average/Poor -> Best = Good (100%)';

  static bool get theOutputColumnHoldsAnArrow =>
      outputColumnRaw.contains('->');

  static const int arrowAnnotatedCellsInTheTrack = 7;

  static bool get theCountReachesSeven => arrowAnnotatedCellsInTheTrack == 7;

  static bool get theFieldIsOnTheAllowlist =>
      !HabotTrackingSdk.permits('device_id');

  static double get quality =>
      theIdentifierIsAppScoped && itDoesNotOutliveTheInstall ? 100 : 0;

  static String get qualitativeOutput =>
      quality == 100 ? 'Good' : 'Average';

  static const String columnNote =
      'COLUMN NOTE: this row asks the gateway to silently capture a unique '
      'mobile device ID, which neither platform supplies to an ordinary '
      'application -- so what was built is an app-scoped install identifier '
      'that answers the duplicate-submission question and nothing else, and '
      'the capture is disclosed on the surface Step 417 named, the second row '
      'in this batch whose literal reading would build surveillance; its band '
      'writes floor and optimal as percentages against a ceiling of 1; its '
      'Best Qualitative Output cell carries an arrow; and its lower half holds '
      'a Domain Expertise line and three numbered sub-cells that belong to a '
      'network-perimeter row. Atomic Step: "Configure the mobile application '
      'network gateway to silently capture the unique mobile device ID upon '
      'submission."';

  static Map<String, bool> get obligations => <String, bool>{
        'no hardware or advertising identifier is read':
            theHardwareIdIsUnavailable && noFingerprintIsAssembled,
        'the identifier is app-scoped': theIdentifierIsAppScoped,
        'it cannot be joined across applications':
            itCannotBeJoinedAcrossApps,
        'it does not outlive the install': itDoesNotOutliveTheInstall,
        'the capture is disclosed': notSilentInTheOtherSense,
        'and it is not on the telemetry allowlist': theFieldIsOnTheAllowlist,
      };

  static Map<String, bool> get checks => <String, bool>{
        'four identifier kinds assessed, one chosen':
            everyKindIsAssessed &&
                chosen == HabotIdentifierKind.appScopedInstall,
        'the platform does not supply a permanent device id':
            theHardwareIdIsUnavailable && noFingerprintIsAssembled,
        'and a fingerprint is the same act under another name':
            platformNote.contains('same act under a different name'),
        'the gateway needs less than the instruction asks for':
            theNeedIsNarrowerThanTheInstruction && propertiesDeclared == 6,
        'the identifier is app-scoped and cannot be joined':
            theIdentifierIsAppScoped && itCannotBeJoinedAcrossApps,
        'it does not outlive the install':
            itDoesNotOutliveTheInstall &&
                designNote.contains('one false negative'),
        'silence as an implementation property is kept':
            silentInTheBuildableSense && theWordWasSplitAtStep417,
        'silence as secrecy is refused for the second time':
            notSilentInTheOtherSense &&
                secondRefusalInThisBatch &&
                theDisclosureSurfaceIsTheOneStep417Named,
        'the band mixes units and the output carries an arrow':
            theBandMixesUnits &&
                theOutputColumnHoldsAnArrow &&
                theCountReachesSeven,
        'six obligations, all met, giving Good':
            obligations.length == 6 &&
                obligations.values.every((bool b) => b) &&
                qualitativeOutput == 'Good' &&
                quality == 100,
      };
}
