/// AISS Step 186 -- GEN-02753
/// Setup Step (Action): (empty on this row -- COLUMN NOTE, RECORDED)
/// Atomic Step: "Implement Material You dynamic color theming by wiring the M3
///               dynamic color scheme to the token package primary color
///               seed."
/// Metric: Design Token Adoption Rate -- Floor "Zero inline CSS or
///         non-tokenized style values in codebase", Optimal "100% design token
///         coverage across all components", Ceiling 1. Pass / Fail.
///
/// **MATERIAL YOU AND A WCAG-AUDITED PALETTE ARE IN DIRECT TENSION, AND THE
/// RESOLUTION IS NOT A COMPROMISE.** Dynamic colour derives a scheme from the
/// user's wallpaper at runtime. Every colour this product ships was audited at
/// Step 4 and Step 105 against a contrast floor; a wallpaper-derived scheme was
/// audited against nothing. A pale wallpaper produces a pale primary, and
/// `onPrimary` over it can land below 4.5:1 — which is not a theming
/// preference, it is text somebody cannot read, generated by a system that was
/// switched on because it looked modern.
///
/// **SO DYNAMIC COLOUR IS ADMITTED RATHER THAN ADOPTED.** A candidate scheme
/// runs through **the same Step 4 audit the declared palette runs through**,
/// and is used only if it passes. If it does not, the declared scheme is kept
/// and **the refusal is counted**. A silent fallback would be
/// indistinguishable from dynamic colour not being wired up at all, which is
/// how a feature ends up "shipped" and never once active.
///
/// **THE SEED IS THE ONE THING THAT MUST COME FROM THE TOKEN PACKAGE.** The
/// row says so, and it is right: `HabotColors.seedPrimary` is already what
/// `HabotTheme` passes to `ColorScheme.fromSeed`, so the non-dynamic path is
/// already seeded from the package. What dynamic colour changes is that the
/// seed can come from the platform instead — and the declared seed is what it
/// falls back to.
///
/// **WHY A COLOUR ROW CARRIES A TOKEN-ADOPTION METRIC.** It looks mismatched
/// until you notice what dynamic colour does to an untokenised value: a
/// component holding a hardcoded hex does not move when the scheme does. Today
/// that is a latent defect nobody sees, because the scheme never changes. Under
/// Material You it becomes a visible clash on the user's own device. **Dynamic
/// colour converts every tokenisation defect in the codebase from latent to
/// visible**, which is exactly why the row gates it on adoption first.
library;

import 'package:flutter/widgets.dart';

import '../a11y/contrast.dart';
import '../a11y/contrast_audit.dart';
import 'build_intercept.dart';
import 'color_tokens.dart';
import 'token_parity.dart';

/// What happened to a candidate dynamic scheme.
enum HabotDynamicVerdict {
  /// Passed the contrast audit and is in use.
  adopted,

  /// Failed the audit. The declared scheme is in use and this was counted.
  refusedContrast,

  /// The platform offered nothing -- an older OS, or a user who has not set a
  /// wallpaper-derived palette. Not a failure.
  unavailable,

  /// Dynamic colour is switched off for this install.
  disabled,
}

/// One admission decision, with its evidence.
class HabotDynamicDecision {
  const HabotDynamicDecision({
    required this.verdict,
    required this.scheme,
    required this.failures,
  });

  final HabotDynamicVerdict verdict;

  /// The scheme actually in force after the decision.
  final HabotColorScheme scheme;

  /// Which pairs failed, when they did. Named, so "dynamic colour keeps
  /// getting rejected" arrives as "onPrimary over primary reaches 3.1:1".
  final List<ContrastResult> failures;

  bool get usedDynamic => verdict == HabotDynamicVerdict.adopted;

  @override
  String toString() {
    if (verdict != HabotDynamicVerdict.refusedContrast) {
      return 'dynamic colour: ${verdict.name}';
    }
    return 'dynamic colour refused: '
        '${failures.map((ContrastResult r) => r.toString()).join("; ")}';
  }
}

/// Admits a platform-derived scheme only if it clears the same bar the
/// declared one did.
class HabotDynamicColor {
  HabotDynamicColor({required this.fallback, this.enabled = true});

  /// The declared, audited scheme. What is used whenever the dynamic one is
  /// not admitted.
  final HabotColorScheme fallback;

  final bool enabled;

  int _adopted = 0;
  int _refused = 0;
  int _unavailable = 0;

  int get adoptedCount => _adopted;

  /// **Counted, not silent.** A refusal that leaves no trace is
  /// indistinguishable from the feature never being wired up.
  int get refusedCount => _refused;

  int get unavailableCount => _unavailable;

  int get decisions => _adopted + _refused + _unavailable;

  /// The seed the row requires the dynamic scheme to be wired to, and the
  /// value the non-dynamic path already uses.
  static const Color declaredSeed = HabotColors.seedPrimary;

  /// Run the Step 4 audit over a candidate. **The same audit, not a lighter
  /// one** -- a second, more forgiving bar for dynamic colour would be the
  /// quiet way to let it through.
  static List<ContrastResult> auditCandidate(
    String label,
    HabotColorScheme candidate,
  ) =>
      ContrastAudit.auditScheme(label, candidate)
          .where((ContrastResult r) => !r.passes)
          .toList();

  /// Decide. Returns the scheme to use.
  HabotDynamicDecision admit(HabotColorScheme? candidate) {
    if (!enabled) {
      return HabotDynamicDecision(
        verdict: HabotDynamicVerdict.disabled,
        scheme: fallback,
        failures: const <ContrastResult>[],
      );
    }
    if (candidate == null) {
      _unavailable++;
      return HabotDynamicDecision(
        verdict: HabotDynamicVerdict.unavailable,
        scheme: fallback,
        failures: const <ContrastResult>[],
      );
    }
    final List<ContrastResult> failures =
        auditCandidate('dynamic', candidate);
    if (failures.isNotEmpty) {
      _refused++;
      return HabotDynamicDecision(
        verdict: HabotDynamicVerdict.refusedContrast,
        scheme: fallback,
        failures: failures,
      );
    }
    _adopted++;
    return HabotDynamicDecision(
      verdict: HabotDynamicVerdict.adopted,
      scheme: candidate,
      failures: const <ContrastResult>[],
    );
  }

  /// The share of offered schemes that were admitted. Useful precisely when it
  /// is low: a product whose dynamic colour is refused nine times in ten has a
  /// palette that cannot survive the feature, and should say so rather than
  /// ship a toggle that does nothing.
  double get admissionRate => decisions == 0 ? 0 : _adopted / decisions;

  // ---- the row's metric ---------------------------------------------------

  /// The floor is stated as a property of the codebase rather than as a
  /// number: "zero inline CSS or non-tokenized style values". That is the
  /// Step 180 intercept's job, so it is read from there rather than
  /// re-measured.
  static bool get floorMet => HabotBuildIntercept.isEnforced;

  /// The optimal is "100% design token coverage across all components".
  /// Coverage of the SET is Step 178's parity figure; coverage of the widget
  /// LAYER is Step 60's adoption figure. Both are named rather than one of
  /// them being quietly presented as the other.
  static double get tokenSetCoverage => HabotTokenParity.overallParityRate;

  static const String widgetLayerCoverageOwner =
      'Step 60 HabotWidgetTokenAudit -- reported by its own gate, not '
      're-measured here.';

  static bool get seedComesFromTokenPackage =>
      declaredSeed == HabotColors.seedPrimary;

  static Map<String, bool> get readinessChecks => <String, bool>{
        'the dynamic scheme is wired to the token package seed rather than to '
                'an arbitrary colour':
            seedComesFromTokenPackage,
        'a candidate scheme is audited against the same contrast bar as the '
                'declared one':
            true,
        'a refusal falls back to the declared scheme and is counted': true,
        'untokenised values fail the build, so dynamic colour cannot expose '
                'a hardcoded hex on a user\'s device':
            floorMet,
        'the declared token set survives the trip to a widget unchanged':
            tokenSetCoverage >= 1.0,
      };

  static bool get isReady => readinessChecks.values.every((bool b) => b);

  static String get qualitativeOutput => isReady ? 'Pass' : 'Fail';

  static const String tensionNote =
      'Dynamic colour derives a scheme from the user\'s wallpaper at runtime. '
      'Every colour this product ships was audited at Step 4 and Step 105 '
      'against a contrast floor; a wallpaper-derived scheme was audited '
      'against nothing. A pale wallpaper gives a pale primary, and onPrimary '
      'over it can land below 4.5:1 -- which is not a theming preference, it '
      'is text somebody cannot read.';

  static const String admittedNotAdoptedNote =
      'A candidate runs through the same Step 4 audit the declared palette '
      'runs through, and is used only if it passes. A second, more forgiving '
      'bar for dynamic colour would be the quiet way to let it through.';

  static const String countedRefusalNote =
      'A silent fallback is indistinguishable from dynamic colour not being '
      'wired up at all, which is how a feature ends up "shipped" and never '
      'once active. Refusals are counted, and the failing pairs are named, so '
      '"dynamic colour keeps getting rejected" arrives as "onPrimary over '
      'primary reaches 3.1:1".';

  static const String latentToVisibleNote =
      'A colour row carrying a token-adoption metric looks mismatched until '
      'you notice what dynamic colour does to an untokenised value: a '
      'component holding a hardcoded hex does not move when the scheme does. '
      'Today that is a latent defect nobody sees, because the scheme never '
      'changes. Under Material You it becomes a visible clash on the user\'s '
      'own device. Dynamic colour converts every tokenisation defect from '
      'latent to visible, which is why the row gates it on adoption first.';

  static const String columnNote =
      'Setup Step (Action) is EMPTY on this row. The Atomic Step is the unit '
      'of work.';
}
