include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    avoid_relative_lib_imports: error

linter:
  rules:
    # Package Architecture & Modular Library Consumption Rules
    - avoid_relative_lib_imports
    - avoid_unnecessary_containers
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - use_key_in_widget_constructors
    - cancel_subscriptions
    - close_sinks
    - unnecessary_const
    - unnecessary_new
